---
  - name: Add fs.file
    sysctl:
      name: fs.file-max
      value: "{{ fs_files_max }}"
      state: present

  - name: Add somaxconn
    sysctl:
      name: net.core.somaxconn
      value: "{{ somaxconn }}"
      state: present
      reload: yes