---
  - name: Delete default from nginx sites-available
    file:
      dest: /etc/nginx/sites-available/default
      state: absent

  - name: Add default to nginx sites-available
    copy:
      src: 'files/default'
      dest: '/etc/nginx/sites-available/default'

  - name: Delete default from nginx site-enabled
    file:
      dest: /etc/nginx/sites-enabled/default
      state: absent

  - name: Create a default symbolic link
    file:
      src: /etc/nginx/sites-available/default
      dest: /etc/nginx/sites-enabled/default
      state: link
    notify: Restart NGINX service